target: motGPT.archs.mld_vae.MldVae
params:
  arch: 'encoder_decoder'
  ff_size: 1024
  num_layers: 9
  num_heads: 4
  dropout: 0.1
  normalize_before: false
  activation: 'gelu'
  position_embedding: 'learned'
  latent_dim: [1, 256] # latent dimension
  code_num: 512
  guidance_scale: 3.0 #
  guidance_uncondp: 0.1 # 0.1 0.25
  datatype: ${DATASET.target}  # 'humanml3d', 'motionx'

  nfeats: ${DATASET.NFEATS}
  ablation: ${ABLATION}